export const SET_STORY_LIST_REQUEST = "SET_STORY_LIST_REQUEST";
export const SET_STORY_LIST_SUCCESS = "SET_STORY_LIST_SUCCESS";
export const SET_STORY_LIST_FAIL = "SET_STORY_LIST_FAIL";

export const SEARCH_STORIES_REQUEST = "SEARCH_STORIES_REQUEST";
export const SEARCH_STORIES_SUCCESS = "SEARCH_STORIES_SUCCESS";
export const SEARCH_STORIES_FAIL = "SEARCH_STORIES_FAIL";

export const PREVIUOS_PAGE_REQUEST = "PREVIUOS_PAGE_REQUEST";
export const PREVIUOS_PAGE_SUCCESS = "PREVIUOS_PAGE_SUCCESS";
export const PREVIOUS_PAGE_FAIL = "PREVIOUS_PAGE_FAIL";

export const NEXT_PAGE_REQUEST = "NEXT_PAGE_REQUEST";
export const NEXT_PAGE_SUCCESS = "NEXT_PAGE_SUCCESS";
export const NEXT_PAGE_FAIL = "NEXT_PAGE_FAIL";
